WIP: Read all data from the SSL server
smartdevicelink/sdl_security_ios pull request #46
Opened 2019-11-19 20:54 UTC by NicoleYarroch

Fixes #41 

This PR is **not ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
Smoke tests performed.

### Summary
* Reading data from the SSL server is now done in a while loop. If there is an error reading the data, then another attempt will be made to read the data instead of erroring out. 

### Changelog
##### Enhancements
* All encrypted and unencrypted data is now read from the SSL server.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2019-11-21 20:25 UTC, joeljfischer requested changes
I don't have a good way to test this project at this point. Do you have recommendations? Should I trust that you've done it well?

2019-11-21 20:25 UTC, joeljfischer commented on SDLSecurity/SDLTLSEngine.m
> +- (int)sdlsec_writeToSSLServerUnencryptedData:(NSData *)data withError:(NSError * __autoreleasing*)error {
```suggestion
- (int)sdlsec_writeToSSLServerWithUnencryptedData:(NSData *)data withError:(NSError * __autoreleasing*)error {
```

2019-11-25 19:24 UTC, NicoleYarroch commented on SDLSecurity/SDLTLSEngine.m
> +- (int)sdlsec_writeToSSLServerUnencryptedData:(NSData *)data withError:(NSError * __autoreleasing*)error {
Fixed. Renamed.

2021-07-01 19:06 UTC, joeljfischer approved these changes

2021-07-01 19:07 UTC, merged