Static build fix
smartdevicelink/sdl_security_ios pull request #63
Opened 2021-08-23 13:23 UTC by FrankElias77

Fixes #56 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Tested the iphone-simulator build with the iOS encryption test app

### Summary
Wrap the different archive files for different architectures in and .xcframework type of file.

### Changelog
##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* N/A

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-09-09 16:07 UTC, joeljfischer requested changes
This project works on device and simulator, but only if you build the static library separately. We need to have one build to hand to developers, we can't require them to build either device or simulator and swap `.a` files.

Best option: Automate a process to build an `xcframework` to hand to devs like we are using in the security library itself.

Next best: Document a manual process to build that `xcframework`

If neither of those work, we need to find another solution.

2021-09-15 16:00 UTC, joeljfischer requested changes

2021-09-15 16:00 UTC, joeljfischer commented on README.md
> +1. Locate the **SDLSecurityStatic.xcframework** file in your project directory through finder. The .xcframework file does contain Headers which could be linked in your project's build settings (**Bui
```suggestion
1. Locate the **SDLSecurityStatic.xcframework** file in the root directory of the project with Finder. The `.xcframework` file contains Headers which must be linked in the app's build settings (**Build Settings > Header Search Paths**). For Swift apps, the headers will need to be imported in the bridging header for the app.
```

Please note that while I've kept the header search paths section here, in my testing I *did not* have to set the header search paths. Please test again, it would be nice to remove this if it's not needed.

2021-09-15 16:00 UTC, joeljfischer commented on README.md
> +1. Alternatively you can locate the header files needed manually, right click and select **Show in Finder** for the following header files **SDLSecurityConstants.h** and **SDLSecurityManager.h**.
```suggestion
1. Alternatively you can locate the header files needed manually, right click and select **Show in Finder** for the following header files **SDLSecurityConstants.h** and **SDLSecurityManager.h**. They will need to be dragged into the app project. For Swift apps, the headers will need to be imported in the bridging header for the app.
```

2021-09-15 16:00 UTC, joeljfischer commented on README.md
> +1. In Xcode, drag and drop the following 3 files into your project: **SDLSecurityStatic.xcframework**, **SDLSecurityConstants.h** and **SDLSecurityManager.h** (or their equivalents after OEM naming m
```suggestion
1. In Xcode, drag and drop the following file into your project: **SDLSecurityStatic.xcframework** (or its equivalent after OEM naming modifications are made).
```

2021-09-16 19:29 UTC, FrankElias77 commented on README.md
> +1. Locate the **SDLSecurityStatic.xcframework** file in your project directory through finder. The .xcframework file does contain Headers which could be linked in your project's build settings (**Bui
It does look like the .h files are getting recognized without setting the header search path

2021-09-16 19:33 UTC, FrankElias77 commented on README.md
> +1. Locate the **SDLSecurityStatic.xcframework** file in your project directory through finder. The .xcframework file does contain Headers which could be linked in your project's build settings (**Bui
Maybe we can leave it as a hint in case xcode was heaving issues detecting them?

2021-09-17 12:55 UTC, joeljfischer commented on README.md
> +1. Locate the **SDLSecurityStatic.xcframework** file in your project directory through finder. The .xcframework file does contain Headers which could be linked in your project's build settings (**Bui
I don't think it's necessary, we can remove it.

2021-09-17 13:12 UTC, joeljfischer requested changes

2021-09-17 13:12 UTC, joeljfischer commented on README.md
> +1. Alternatively you can locate the header files needed manually, right click and select **Show in Finder** for the following header files **SDLSecurityConstants.h** and **SDLSecurityManager.h**. The
```suggestion
```

2021-09-17 13:12 UTC, joeljfischer commented on README.md
> +1. In Xcode, drag and drop the following file into your project: **SDLSecurityStatic.xcframework** (or its equivalent after OEM naming modifications are made).
```suggestion
1. Drag the **SDLSecurityStatic.xcframework** (or its equivalent after OEM naming modifications are made) file to the app project in Xcode. The `.xcframework` file contains the static library and header files. For Swift apps, the headers will need to be imported in the bridging header for the app.
```

2021-09-17 13:12 UTC, joeljfischer commented on README.md
> +1. Locate the **SDLSecurityStatic.xcframework** file in the root directory of the project with Finder. The `.xcframework` file contains Headers. For Swift apps, the headers will need to be imported i
```suggestion
1. Locate the **SDLSecurityStatic.xcframework** file in the root directory of the project with Finder. The `.xcframework` folder contains the static library builds and header files in a structure that Xcode 12+ can understand.
```

2021-09-20 13:27 UTC, joeljfischer approved these changes

2021-09-20 13:27 UTC, merged