OpenSSL version updated
smartdevicelink/sdl_security_ios pull request #69
Opened 2022-01-04 21:03 UTC by FrankElias77

Fixes #68 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Tested with sending encrypted add command

### Summary
Update OpenSSL header files
Deprecated calls are fixed

### Changelog
##### Breaking Changes
* Update OpenSSL header files
Deprecated calls are fixed

##### Enhancements
* N/A

##### Bug Fixes
* N/A

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-01-05 15:53 UTC, joeljfischer requested changes
Isn't building for me with issues like this:

```
In file included from /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/SDLSecurity/SDLTLSEngine.m:11:
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bio.h:687:1: error: expected function body after function declarator
DEPRECATEDIN_1_1_0(int BIO_get_port(const char *str, unsigned short *port_ptr))
^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bio.h:699:55: warning: declaration of 'union BIO_sock_info_u' will not be visible outside of this function [-Wvisibility]
                  enum BIO_sock_info_type type, union BIO_sock_info_u *info);
                                                      ^
In file included from /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/SDLSecurity/SDLTLSEngine.m:12:
In file included from /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/ssl.h:20:
In file included from /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/x509.h:18:
In file included from /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/evp.h:28:
In file included from /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/objects.h:15:
In file included from /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/asn1.h:23:
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:183:43: error: unknown type name 'BN_ULONG'
int BN_abs_is_word(const BIGNUM *a, const BN_ULONG w);
                                          ^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:186:39: error: unknown type name 'BN_ULONG'
int BN_is_word(const BIGNUM *a, const BN_ULONG w);
                                      ^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:214:22: error: unknown type name 'BN_ULONG'
int BN_num_bits_word(BN_ULONG l);
                     ^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:266:1: error: unknown type name 'BN_ULONG'
BN_ULONG BN_mod_word(const BIGNUM *a, BN_ULONG w);
^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:266:39: error: unknown type name 'BN_ULONG'
BN_ULONG BN_mod_word(const BIGNUM *a, BN_ULONG w);
                                      ^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:267:1: error: unknown type name 'BN_ULONG'
BN_ULONG BN_div_word(BIGNUM *a, BN_ULONG w);
^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:267:33: error: unknown type name 'BN_ULONG'
BN_ULONG BN_div_word(BIGNUM *a, BN_ULONG w);
                                ^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:268:28: error: unknown type name 'BN_ULONG'
int BN_mul_word(BIGNUM *a, BN_ULONG w);
                           ^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:269:28: error: unknown type name 'BN_ULONG'
int BN_add_word(BIGNUM *a, BN_ULONG w);
                           ^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:270:28: error: unknown type name 'BN_ULONG'
int BN_sub_word(BIGNUM *a, BN_ULONG w);
                           ^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:271:28: error: unknown type name 'BN_ULONG'
int BN_set_word(BIGNUM *a, BN_ULONG w);
                           ^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:272:1: error: unknown type name 'BN_ULONG'
BN_ULONG BN_get_word(const BIGNUM *a);
^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:288:37: error: unknown type name 'BN_ULONG'
int BN_mod_exp_mont_word(BIGNUM *r, BN_ULONG a, const BIGNUM *p,
                                    ^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:323:24: error: unknown type name 'BN_ULONG'
void BN_consttime_swap(BN_ULONG swap, BIGNUM *a, BIGNUM *b, int nwords);
                       ^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:332:1: error: expected function body after function declarator
DEPRECATEDIN_0_9_8(int
^
/Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:403:1: error: expected function body after function declarator
```

2022-01-05 19:22 UTC, FrankElias77 commented
> Isn't building for me with issues like this:
> 
> ```
> In file included from /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/SDLSecurity/SDLTLSEngine.m:11:
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bio.h:687:1: error: expected function body after function declarator
> DEPRECATEDIN_1_1_0(int BIO_get_port(const char *str, unsigned short *port_ptr))
> ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bio.h:699:55: warning: declaration of 'union BIO_sock_info_u' will not be visible outside of this function [-Wvisibility]
>                   enum BIO_sock_info_type type, union BIO_sock_info_u *info);
>                                                       ^
> In file included from /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/SDLSecurity/SDLTLSEngine.m:12:
> In file included from /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/ssl.h:20:
> In file included from /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/x509.h:18:
> In file included from /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/evp.h:28:
> In file included from /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/objects.h:15:
> In file included from /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/asn1.h:23:
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:183:43: error: unknown type name 'BN_ULONG'
> int BN_abs_is_word(const BIGNUM *a, const BN_ULONG w);
>                                           ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:186:39: error: unknown type name 'BN_ULONG'
> int BN_is_word(const BIGNUM *a, const BN_ULONG w);
>                                       ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:214:22: error: unknown type name 'BN_ULONG'
> int BN_num_bits_word(BN_ULONG l);
>                      ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:266:1: error: unknown type name 'BN_ULONG'
> BN_ULONG BN_mod_word(const BIGNUM *a, BN_ULONG w);
> ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:266:39: error: unknown type name 'BN_ULONG'
> BN_ULONG BN_mod_word(const BIGNUM *a, BN_ULONG w);
>                                       ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:267:1: error: unknown type name 'BN_ULONG'
> BN_ULONG BN_div_word(BIGNUM *a, BN_ULONG w);
> ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:267:33: error: unknown type name 'BN_ULONG'
> BN_ULONG BN_div_word(BIGNUM *a, BN_ULONG w);
>                                 ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:268:28: error: unknown type name 'BN_ULONG'
> int BN_mul_word(BIGNUM *a, BN_ULONG w);
>                            ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:269:28: error: unknown type name 'BN_ULONG'
> int BN_add_word(BIGNUM *a, BN_ULONG w);
>                            ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:270:28: error: unknown type name 'BN_ULONG'
> int BN_sub_word(BIGNUM *a, BN_ULONG w);
>                            ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:271:28: error: unknown type name 'BN_ULONG'
> int BN_set_word(BIGNUM *a, BN_ULONG w);
>                            ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:272:1: error: unknown type name 'BN_ULONG'
> BN_ULONG BN_get_word(const BIGNUM *a);
> ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:288:37: error: unknown type name 'BN_ULONG'
> int BN_mod_exp_mont_word(BIGNUM *r, BN_ULONG a, const BIGNUM *p,
>                                     ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:323:24: error: unknown type name 'BN_ULONG'
> void BN_consttime_swap(BN_ULONG swap, BIGNUM *a, BIGNUM *b, int nwords);
>                        ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:332:1: error: expected function body after function declarator
> DEPRECATEDIN_0_9_8(int
> ^
> /Users/joelfischer/Developer/livio/sdl/sdl_security_ios/Dependencies/OpenSSL/include/openssl/bn.h:403:1: error: expected function body after function declarator
> ```

I did encounter this issue at first but then it disappeared after doing a clean rebuild
Does this issue persists if you clone this repo again?

2022-01-05 20:34 UTC, joeljfischer commented
@FrankElias77 Still happening after a re-clone, but only on the static build

2022-01-07 16:44 UTC, joeljfischer approved these changes

2022-01-07 16:46 UTC, joeljfischer approved these changes

2022-01-07 16:46 UTC, merged